version: '3'

services:
  web:
    container_name: mil_site
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    volumes:
      - static_files_volume:/home/appuser/web/static
    env_file:
      - .env.prod
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - backend_net

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env-db.prod
    ports:
      - 5432:5432
    networks:
      - backend_net

  db-admin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - .env.prod
    ports:
      - 8080:80
    networks:
      - backend_net

  nginx:
    build: ./nginx
    volumes:
      - static_files_volume:/home/appuser/web/static
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - backend_net
      
volumes:
  postgres_data:
  static_files_volume:

networks:
  backend_net:
    driver: bridge