# Generated by Django 2.2.5 on 2019-09-04 10:05

from django.db import migrations


def load_ranks(apps, schema_editor):
    Rank = apps.get_model('reports', 'Rank')

    ranks_list = [
        ['молодший лейтенант', 'молодшому лейтенанту', 'молодшого лейтенанта'],
        ['лейтенант', 'лейтенанту', 'лейтенанта'],
        ['старший лейтенант', 'старшому лейтенанту', 'старшого лейтенанта'],
        ['капітан', 'капітану', 'капітана'],
        ['майор', 'майору', 'майора'],
        ['підполковник', 'підполковнику', 'підполковника'],
        ['полковник', 'полковнику', 'полковника'],
    ]

    for rank_pair in ranks_list:
        record = Rank(name=rank_pair[0], to_name=rank_pair[1], for_name=rank_pair[2])
        record.save()


def delete_ranks(apps, schema_editor):
    Rank = apps.get_model('reports', 'Rank')
    Rank.objects.all().delete()


# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

def load_units(apps, schema_editor):
    Unit = apps.get_model('reports', 'Unit')

    units_list = {
        'центру адміністраторів безпеки ІТС': [
            'відділу адміністраторів інформаційних систем',
            'відділу адміністраторів захищених систем'
        ],
        'центру кібернетичної безпеки ІТС': [
            'відділу аналізу інцидентів кібернетичної безпеки',
            'відділу моніторингу інцидентів кібернетичної безпеки',
        ],
    }

    main_unit = Unit(name='військової частини А0334')
    main_unit.save()

    for center, units in units_list.items():
        record = Unit(name=center, parent_unit=main_unit)
        record.save()
        for unit in units:
            record2 = Unit(name=unit, parent_unit=record)
            record2.save()


def delete_units(apps, schema_editor):
    Unit = apps.get_model('reports', 'Unit')
    Unit.objects.all().delete()


# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

# def load_positions(apps, schema_editor):
#     """currently not in use"""
#     Position = apps.get_model('reports', 'Position')
#     Unit = apps.get_model('reports', 'Unit')
#
#     units = Unit.objects.all()
#     main_unit = units.filter(name='військової частини А0334')[0]
#     admins_main_unit = units.filter(name='центру адміністраторів безпеки ІТС')[0]
#
#     Position(position_title='командир',
#              unit=main_unit,
#              position_tail='',
#              temp_supervisor=True
#              ).save()
#
#     Position(position_title='начальник',
#              unit=admins_main_unit,
#              position_tail='',
#              temp_supervisor=True
#              ).save()
#
#
# def delete_positions(apps, schema_editor):
#     Position = apps.get_model('reports', 'Position')
#     Position.objects.all().delete()

# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

def load_servicemans(apps, schema_editor):
    Serviceman = apps.get_model('reports', 'Serviceman')
    Rank = apps.get_model('reports', 'Rank')
    Unit = apps.get_model('reports', 'Unit')
    Position = apps.get_model('reports', 'Position')

    ranks = Rank.objects.all()
    jun_lt_rank = ranks.filter(name='молодший лейтенант').first()
    lt_rank = ranks.filter(name='лейтенант').first()
    senior_lt_rank = ranks.filter(name='старший лейтенант').first()
    capitan_rank = ranks.filter(name='капітан').first()
    major_rank = ranks.filter(name='майор').first()
    lt_col_rank = ranks.filter(name='підполковник').first()
    col_rank = ranks.filter(name='полковник').first()

    units = Unit.objects.all()
    main_unit = units.filter(name='військової частини А0334').first()
    admins_main_unit = units.filter(name='центру адміністраторів безпеки ІТС').first()
    cyber_main_unit = units.filter(name='центру кібернетичної безпеки ІТС').first()
    admins_unit_section_1 = units.filter(name='відділу адміністраторів інформаційних систем').first()
    admins_unit_section_2 = units.filter(name='відділу адміністраторів захищених систем').first()

    #####################################################################################

    pos_main_unit_commander = Position(position_title='командир',
                                       unit=main_unit,
                                       supervisor=True,
                                       temp_supervisor=False
                                       )
    pos_main_unit_commander.save()

    pos_admins_main_unit_boss = Position(position_title='начальник',
                                         unit=admins_main_unit,
                                         supervisor=True,
                                         temp_supervisor=False
                                         )
    pos_admins_main_unit_boss.save()

    pos_admins_main_unit_deputy = Position(position_title='начальник',
                                         unit=admins_main_unit,
                                         supervisor=False,
                                         temp_supervisor=True
                                         )
    pos_admins_main_unit_deputy.save()

    pos_cyber_main_unit_boss = Position(position_title='начальник',
                                        unit=cyber_main_unit,
                                        supervisor=True,
                                        temp_supervisor=False
                                        )
    pos_cyber_main_unit_boss.save()

    pos_admins_unit_section_1_boss = Position(position_title='начальник',
                                              unit=admins_unit_section_1,
                                              position_tail=' - заступник начальника',
                                              supervisor=True,
                                              temp_supervisor=False
                                              )
    pos_admins_unit_section_1_boss.save()

    pos_admins_unit_section_2_boss = Position(position_title='начальник',
                                              unit=admins_unit_section_2,
                                              supervisor=True,
                                              temp_supervisor=False
                                              )
    pos_admins_unit_section_2_boss.save()

    pos_admins_unit_section_1_senior_officer = Position(position_title='старший офіцер',
                                                        unit=admins_unit_section_1,
                                                        temp_supervisor=False
                                                        )
    pos_admins_unit_section_1_senior_officer.save()

    pos_admins_unit_section_2_senior_officer = Position(position_title='старший офіцер',
                                                        unit=admins_unit_section_2,
                                                        temp_supervisor=False
                                                        )
    pos_admins_unit_section_2_senior_officer.save()

    pos_admins_unit_section_1_officer = Position(position_title='офіцер',
                                                 unit=admins_unit_section_1,
                                                 temp_supervisor=False
                                                 )
    pos_admins_unit_section_1_officer.save()

    pos_admins_unit_section_2_officer = Position(position_title='офіцер',
                                                 unit=admins_unit_section_2,
                                                 temp_supervisor=False
                                                 )
    pos_admins_unit_section_2_officer.save()

    # service duty officers
    pos_admins_unit_duty_officer = Position(position_title='Адміністратор безпеки АСУ ЗС України (НЧО-471)',
                                            unit=admins_main_unit,
                                            temp_supervisor=False
                                            )
    pos_admins_unit_duty_officer.save()

    pos_cyber_unit_duty_officer = Position(position_title='Начальник зміни (НЧО-51)',
                                           unit=cyber_main_unit,
                                           temp_supervisor=False
                                           )
    pos_cyber_unit_duty_officer.save()

    #####################################################################################

    Serviceman(first_name='Руслан',
               last_name='Денесюк',
               to_first_name='Руслану',
               to_last_name='Денесюку',
               rank=col_rank,
               unit=main_unit,
               position=pos_main_unit_commander
               ).save()

    Serviceman(first_name='Дмитро',
               last_name='Тюркін',
               to_first_name='Дмитру',
               to_last_name='Тюркіну',
               for_first_name='Дмитра',
               for_last_name='Тюркіна',
               rank=lt_col_rank,
               unit=admins_main_unit,
               position=pos_admins_main_unit_boss
               ).save()

    Serviceman(first_name='Дмитро',
               last_name='Павленко',
               to_first_name='Дмитру',
               to_last_name='Павленку',
               for_first_name='_____',
               for_last_name='______',
               rank=lt_col_rank,
               unit=admins_unit_section_1,
               position=pos_admins_unit_section_1_boss
               ).save()

    Serviceman(first_name='Олександр',
               last_name='Чмутов',
               to_first_name='Олександру',
               to_last_name='Чмутову',
               rank=capitan_rank,
               unit=admins_unit_section_2,
               position=pos_admins_unit_section_2_boss
               ).save()

    Serviceman(first_name='Василь',
               last_name='Шпак',
               to_first_name='Василю',
               to_last_name='Шпаку',
               for_first_name='Шпака',
               for_last_name='Василя',
               rank=capitan_rank,
               unit=admins_unit_section_1,
               position=pos_admins_unit_section_1_senior_officer
               ).save()

    Serviceman(first_name='Віктор',
               last_name='Оркуш',
               to_first_name='Віктору',
               to_last_name='Оркушу',
               for_first_name='Віктора',
               for_last_name='Оркуша',
               rank=capitan_rank,
               unit=admins_unit_section_1,
               position=pos_admins_unit_section_1_senior_officer
               ).save()

    Serviceman(first_name='Євгенія',
               last_name='Куріло',
               to_first_name='Євгенії',
               to_last_name='Куріло',
               for_first_name='Євгенії',
               for_last_name='Куріло',
               rank=senior_lt_rank,
               unit=admins_unit_section_1,
               position=pos_admins_unit_section_1_officer
               ).save()

    Serviceman(first_name='Антон',
               last_name='Назаренко',
               to_first_name='Антону',
               to_last_name='Назаренку',
               for_first_name='Антона',
               for_last_name='Назаренка',
               rank=capitan_rank,
               unit=admins_unit_section_2,
               position=pos_admins_unit_section_2_senior_officer
               ).save()

    Serviceman(first_name='Анастасія',
               last_name='Гримут',
               to_first_name='Анастасії',
               to_last_name='Гримут',
               for_first_name='Анастасії',
               for_last_name='Гримуд',
               rank=senior_lt_rank,
               unit=admins_unit_section_2,
               position=pos_admins_unit_section_1_officer
               ).save()

    Serviceman(first_name='Вадим',
               last_name='Єфіменко',
               to_first_name='Вадиму',
               to_last_name='Єфіменко',
               for_first_name='Єфіменка',
               for_last_name='Вадима',
               rank=lt_rank,
               unit=admins_unit_section_2,
               position=pos_admins_unit_section_2_officer
               ).save()

    Serviceman(first_name='Цабуров',
               last_name='Сергій',
               to_first_name='Цабурову',
               to_last_name='Сергію',
               for_first_name='Цабурова',
               for_last_name='Сергія',
               rank=jun_lt_rank,
               unit=admins_main_unit,
               position=pos_admins_main_unit_deputy
               ).save()


def delete_serviceman(apps, schema_editor):
    Serviceman = apps.get_model('reports', 'Serviceman')
    Serviceman.objects.all().delete()


# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

def load_reports(apps, schema_editor):
    Report = apps.get_model('reports', 'Report')
    Position = apps.get_model('reports', 'Position')
    Serviceman = apps.get_model('reports', 'Serviceman')
    Unit = apps.get_model('reports', 'Unit')

    units = Unit.objects.all()
    main_unit = units.filter(name='військової частини А0334').first()
    admins_main_unit = units.filter(name='центру адміністраторів безпеки ІТС').first()
    cyber_main_unit = units.filter(name='центру кібернетичної безпеки ІТС').first()
    admins_unit_section_1 = units.filter(name='відділу адміністраторів інформаційних систем').first()
    admins_unit_section_2 = units.filter(name='відділу адміністраторів захищених систем').first()

    positions = Position.objects.all()
    pos_main_unit_commander = positions.filter(position_title='командир', unit=main_unit).first()

    pos_admins_main_unit_boss = positions.filter(position_title='начальник',
                                         unit=admins_main_unit,
                                         supervisor=True,
                                         temp_supervisor=False
                                         ).first()

    pos_cyber_main_unit_boss = positions.filter(position_title='начальник',
                                        unit=cyber_main_unit,
                                        supervisor=True,
                                        temp_supervisor=False
                                        ).first()

    Report(
        title="Перенесення терміну щорічної основної відпустки",
        body_sample="""Прошу Вашого клопотання про перенесення мені терміну щорічної основної відпустки за 
            2019 рік з 29 жовтня на 20 грудня 2019 року у зв’язку з сiмейними обставинами.""",
        body_template="""Прошу Вашого клопотання про перенесення мені терміну щорічної основної відпустки за {
                "type": "int"
            } рік з {
                "title": "з якой дати",
                "type": "date"
            } на {
                "title": "на яку дату",
                "type": "date"
            } року у зв’язку з {
                "title": "причина переносу_1",
                "type": "str"
            } або у зв’язку з {
                "title": "причина переносу_2",
                "type": "text"
            }.
            {"type":"rank_first_name_last_name"}
            Шановний {
                "type":"rank_last_name_first_name"
            }, для перенесення терміну щорічної основної відпустки ви маєте зробити речі, які до цього часу не міг зробити ніхто....
            {"type":"first_name_last_name"}
            {"type":"last_name_first_name"}""",
    ).save()

    Report(
        title="Повернення з-за меж гарнiзону",
        body_sample="Доповiдаю, що з-за меж Киiвського гарнiзону прибув та приступив до виконання службових обов'язкiв.",
        body_template="Доповiдаю, що з-за меж Киiвського гарнiзону прибув та приступив до виконання службових обов'язкiв."
    ).save()

    # --------------------- CUSTOM TYPE REPORTS ---------------------
    Report(
        title="(ЦАБ-наряд) Заступають на чергування ЦАБ - НЧО-471 (custom_report_type)",
        type="custom",
        template_name="template_custom_1.docx",
        body_sample="""Доповiдаю, завтра в ЦАБ заступають на чергування наступні люди: ...""",
        body_template="""Доповiдаю, завтра в ЦАБ заступають на чергування наступні люди: ...
            {
                "type": "date"
            }:
            НЧО-471 - {"type":"rank_first_name_last_name"}""",
        default_header_position=pos_main_unit_commander,
        default_footer_position=pos_admins_main_unit_boss
    ).save()

    Report(
        title="(ЦКБ-наряд) Заступають на чергування ЦКБ - НЧО-51 (custom_report_type)",
        template_name="template_custom_1.docx",
        type="custom",
        body_sample="""Доповiдаю, завтра в ЦКБ заступають на чергування наступні люди: ...""",
        body_template="""Доповiдаю, завтра в ЦКБ заступають на чергування наступні люди: ...
                {
                    "type": "date"
                }:
                НЧО-471 - {"type":"rank_first_name_last_name"}""",
        default_header_position=pos_main_unit_commander,
        default_footer_position=pos_cyber_main_unit_boss
    ).save()


def delete_reports(apps, schema_editor):
    Report = apps.get_model('reports', 'Report')
    Report.objects.all().delete()


# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_ranks, delete_ranks),
        migrations.RunPython(load_units, delete_units),
        # migrations.RunPython(load_positions, delete_positions),
        migrations.RunPython(load_servicemans, delete_serviceman),
        migrations.RunPython(load_reports, delete_reports)
    ]
