# Generated by Django 2.2.5 on 2019-10-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', 'filled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.IntegerField(choices=[(0, 'Report_1'), (1, 'Report_2'), (2, 'Report_3')], default='0')),
                ('report_fields', models.CharField(max_length=1024)),
            ],
        ),
    ]
