# Generated by Django 2.2.5 on 2019-09-04 10:05

from django.db import migrations


def load_ranks(apps, schema_editor):
    Rank = apps.get_model('reports', 'Rank')

    # ranks_list = [
    #     'молодший лейтенант',
    #     'лейтенант',
    #     'старший лейтенант',
    #     'капітан',
    #     'майор',
    #     'підполковник',
    #     'полковник',
    # ]
    #
    # for rank_pair in ranks_list:
    #     record = Rank(name=rank_pair)
    #     record.save()

    ranks_list = [
        ['молодший лейтенант', 'молодшому лейтенанту', 'молодшого лейтенанта'],
        ['лейтенант', 'лейтенанту', 'лейтенанта'],
        ['старший лейтенант', 'старшому лейтенанту', 'старшого лейтенанту'],
        ['капітан', 'капітану', 'капітана'],
        ['майор', 'майору', 'майора'],
        ['підполковник', 'підполковнику', 'підполковника'],
        ['полковник', 'полковнику', 'полковника'],
    ]


    for rank_pair in ranks_list:
        record = Rank(name=rank_pair[0], to_name=rank_pair[1], for_name=rank_pair[2])
        record.save()


def delete_ranks(apps, schema_editor):
    Rank = apps.get_model('reports', 'Rank')
    Rank.objects.all().delete()










#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

def load_units(apps, schema_editor):
    Unit = apps.get_model('reports', 'Unit')

    units_list = {
        'центру адміністраторів безпеки ІТС': [
            'відділу адміністраторів інформаційних систем',
            'відділу адміністраторів захищених систем'
        ],
        'центру кібернетичної безпеки ІТС': [
            'відділу аналізу інцидентів кібернетичної безпеки',
            'відділу моніторингу інцидентів кібернетичної безпеки',
        ],
    }

    main_unit = Unit(name='військової частини А0334')
    main_unit.save()

    for center, units in units_list.items():
        record = Unit(name=center, parent_unit=main_unit)
        record.save()
        for unit in units:
            record2 = Unit(name=unit, parent_unit=record)
            record2.save()


def delete_units(apps, schema_editor):
    Unit = apps.get_model('reports', 'Unit')
    Unit.objects.all().delete()










#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

def load_positions(apps, schema_editor):
    """currently not in use"""
    Position = apps.get_model('reports', 'Position')
    Unit = apps.get_model('reports', 'Unit')

    units = Unit.objects.all()
    main_unit = units.filter(name='військової частини А0334')[0]
    admins_main_unit = units.filter(name='центру адміністраторів безпеки ІТС')[0]




    Position(position_title='командир',
             unit=main_unit,
             position_tail='',
             temp_supervisor=True
             ).save()


    Position(position_title='начальник',
             unit=admins_main_unit,
             position_tail='',
             temp_supervisor=True
             ).save()



def delete_positions(apps, schema_editor):
    Position = apps.get_model('reports', 'Position')
    Position.objects.all().delete()








# $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

def load_servicemans(apps, schema_editor):
    Serviceman = apps.get_model('reports', 'Serviceman')
    Rank = apps.get_model('reports', 'Rank')
    Unit = apps.get_model('reports', 'Unit')
    Position = apps.get_model('reports', 'Position')


    ranks = Rank.objects.all()
    jun_lt_rank = ranks.filter(name='молодший лейтенант').first()
    lt_rank = ranks.filter(name='лейтенант').first()
    senior_lt_rank = ranks.filter(name='старший лейтенант').first()
    capitan_rank = ranks.filter(name='капітан').first()
    major_rank = ranks.filter(name='майор').first()
    lt_col_rank = ranks.filter(name='підполковник').first()
    col_rank = ranks.filter(name='полковник').first()


    units = Unit.objects.all()
    main_unit = units.filter(name='військової частини А0334')[0]
    admins_main_unit = units.filter(name='центру адміністраторів безпеки ІТС')[0]
    admins_unit_section_1 = units.filter(name='відділу адміністраторів інформаційних систем')[0]
    admins_unit_section_2 = units.filter(name='відділу адміністраторів захищених систем')[0]


#####################################################################################

    pos_main_unit_commander = Position(position_title='командир',
                                       unit=main_unit,
                                       position_tail='',
                                       supervisor=True,
                                       temp_supervisor = False
                                       )
    pos_main_unit_commander.save()

    pos_admins_main_unit_boss = Position(position_title='начальник',
                                         unit=admins_main_unit,
                                         position_tail='',
                                         supervisor=True,
                                         temp_supervisor=True
                                         )
    pos_admins_main_unit_boss.save()

    pos_admins_unit_section_1_boss = Position(position_title='начальник',
                                              unit=admins_unit_section_1,
                                              position_tail=' - заступник начальника',
                                              supervisor=True,
                                              temp_supervisor=False
                                              )
    pos_admins_unit_section_1_boss.save()

    pos_admins_unit_section_2_boss = Position(position_title='начальник',
                                              unit=admins_unit_section_2,
                                              position_tail='',
                                              supervisor=True,
                                              temp_supervisor=False
                                              )
    pos_admins_unit_section_2_boss.save()

    pos_admins_unit_section_1_senior_officer = Position(position_title='старший офіцер',
                                                        unit=admins_unit_section_1,
                                                        position_tail='',
                                                        temp_supervisor=False
                                                        )
    pos_admins_unit_section_1_senior_officer.save()

    pos_admins_unit_section_2_senior_officer = Position(position_title='старший офіцер',
                                                        unit=admins_unit_section_2,
                                                        position_tail='',
                                                        temp_supervisor=False
                                                        )
    pos_admins_unit_section_2_senior_officer.save()

    pos_admins_unit_section_1_officer = Position(position_title='офіцер',
                                                 unit=admins_unit_section_1,
                                                 position_tail='',
                                                 temp_supervisor=False
                                                 )
    pos_admins_unit_section_1_officer.save()

    pos_admins_unit_section_2_officer = Position(position_title='офіцер',
                                                 unit=admins_unit_section_2,
                                                 position_tail='',
                                                 temp_supervisor=False
                                                 )
    pos_admins_unit_section_2_officer.save()

#####################################################################################

    Serviceman(first_name='Руслан',
               last_name='Денесюк',
               to_first_name='Руслану',
               to_last_name='Денесюку',
               rank=col_rank,
               unit=main_unit,
               position=pos_main_unit_commander
               ).save()

    Serviceman(first_name='Дмитро',
               last_name='Тюркін',
               to_first_name='Дмитру',
               to_last_name='Тюркіну',
               rank=lt_col_rank,
               unit=admins_main_unit,
               position=pos_admins_main_unit_boss
               ).save()

    Serviceman(first_name='Дмитро',
               last_name='Павленко',
               to_first_name='Дмитру',
               to_last_name='Павленку',
               rank=lt_col_rank,
               unit=admins_unit_section_1,
               position=pos_admins_unit_section_1_boss
               ).save()

    Serviceman(first_name='Олександ',
               last_name='Чмутов',
               to_first_name='Олександру',
               to_last_name='Чмутову',
               rank=capitan_rank,
               unit=admins_unit_section_2,
               position=pos_admins_unit_section_2_boss
               ).save()




    Serviceman(first_name='Василь',
               last_name='Шпак',
               to_first_name='Василю',
               to_last_name='Шпаку',
               for_first_name='Шпака',
               for_last_name='Василя',
               rank=capitan_rank,
               unit=admins_unit_section_1,
               position=pos_admins_unit_section_1_senior_officer
               ).save()

    Serviceman(first_name='Віктор',
               last_name='Оркуш',
               to_first_name='Віктору',
               to_last_name='Оркушу',
               for_first_name='Віктора',
               for_last_name='Оркуша',
               rank=capitan_rank,
               unit=admins_unit_section_1,
               position=pos_admins_unit_section_1_senior_officer
               ).save()

    Serviceman(first_name='Євгенія',
               last_name='Куріло',
               to_first_name='Євгенії',
               to_last_name='Куріло',
               for_first_name='Євгенії',
               for_last_name='Куріло',
               rank=senior_lt_rank,
               unit=admins_unit_section_1,
               position=pos_admins_unit_section_1_officer
               ).save()

    Serviceman(first_name='Антон',
               last_name='Назаренко',
               to_first_name='Антону',
               to_last_name='Назаренку',
               for_first_name='Антона',
               for_last_name='Назаренка',
               rank=capitan_rank,
               unit=admins_unit_section_2,
               position=pos_admins_unit_section_2_senior_officer
               ).save()

    Serviceman(first_name='Анастасія',
               last_name='Гримут',
               to_first_name='Анастасії',
               to_last_name='Гримут',
               for_first_name='Анастасії',
               for_last_name='Гримуд',
               rank=senior_lt_rank,
               unit=admins_unit_section_2,
               position=pos_admins_unit_section_1_officer
               ).save()


    Serviceman(first_name='Вадим',
               last_name='Єфіменко',
               to_first_name='Вадиму',
               to_last_name='Єфіменко',
               for_first_name='Єфіменка',
               for_last_name='Вадима',
               rank=lt_rank,
               unit=admins_unit_section_2,
               position=pos_admins_unit_section_2_officer
               ).save()




def delete_serviceman(apps, schema_editor):
    Serviceman = apps.get_model('reports', 'Serviceman')
    Serviceman.objects.all().delete()


#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

def load_reports(apps, schema_editor):
    Report = apps.get_model('reports', 'Report')

    # Report(
    #     title="",
    #     body_sample = "",
    #     body = ""
    # ).save()

    Report(
        title="Перенесення терміну щорічної основної відпустки",
        body_sample="""Прошу Вашого клопотання про перенесення мені терміну щорічної основної відпустки за 
                    2019 рік з 29 жовтня на 20 грудня 2019 року у зв’язку з сiмейними обставинами.""",
        body="""Прошу Вашого клопотання про перенесення мені терміну щорічної основної відпустки за 
                    @_int_за какой год переносится отпуск@ рік з @_date_перенести с@ на @_date_перенести на@ 
                    року у зв’язку з @_str_причина_long@.
                    """,
    ).save()

    Report(
        title="Повернення з-за меж гарнiзону",
        body_sample="Доповiдаю, що з-за меж Киiвського гарнiзону прибув та приступив до виконання службових обов'язкiв.",
        body="Доповiдаю, що з-за меж Киiвського гарнiзону прибув та приступив до виконання службових обов'язкiв."
    ).save()

def delete_reports(apps, schema_editor):
    Report = apps.get_model('reports', 'Report')
    Report.objects.all().delete()

#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_ranks, delete_ranks),
        migrations.RunPython(load_units, delete_units),
        # migrations.RunPython(load_positions, delete_positions),
        migrations.RunPython(load_servicemans, delete_serviceman),
        migrations.RunPython(load_reports, delete_reports)
    ]
