# Generated by Django 3.0.8 on 2020-08-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=255, verbose_name='посада (офіцер, старший офіцер, начальник)')),
                ('position_tail', models.CharField(blank=True, default='', max_length=255, verbose_name='додаткова посада. Наприклад:(заступник начальника, перший заступник командира...)  !!! назву підрозділу НЕ ВКАЗУВАТИ  !!!')),
                ('supervisor', models.BooleanField(blank=True, default=False, null=True, verbose_name='командир/начальник підрозділу')),
                ('temp_supervisor', models.BooleanField(blank=True, default=False, null=True, verbose_name="тимчасово виконуючий обов'язки командира/начальника")),
            ],
            options={
                'verbose_name': 'Посада__',
                'verbose_name_plural': 'Посади',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='військове звання (полковник, лейтенант..)')),
                ('to_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='військове звання, давальний відмінок (полковнику, лейтенанту..)')),
                ('for_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='військове звання, знахідний відмінок (полковника, лейтенанта..)')),
            ],
            options={
                'verbose_name': 'Військові звання__',
                'verbose_name_plural': 'Військові звання',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='назва підрозділу в РОДОВОМУ відміноку (відділу аналізу інцидентів кібернетичної безпеки)')),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Unit', verbose_name='вищій підрозділ (віддліл->центр->..)')),
            ],
            options={
                'verbose_name': 'Підрозділ',
                'verbose_name_plural': 'Підрозділи',
            },
        ),
        migrations.CreateModel(
            name='Serviceman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('to_first_name', models.CharField(max_length=255, verbose_name="Ім'я, давальний відмінок (Петру, Євгенії, Дмитру...)")),
                ('to_last_name', models.CharField(max_length=255, verbose_name='Прізвище, давальний відмінок (Яцуку, Куріло, Павленку...)')),
                ('for_first_name', models.CharField(max_length=255, verbose_name="Ім'я, знахідний відмінок (Петра, Євгенії, Дмитра...)")),
                ('for_last_name', models.CharField(max_length=255, verbose_name='Прізвище, знахідний відмінок (Яцука, Куріло, Павленка...)')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reports.Position', verbose_name='Посада')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reports.Rank', verbose_name='військове звання')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reports.Unit', verbose_name='Підрозділ')),
            ],
            options={
                'verbose_name': 'Військовослужбовці__',
                'verbose_name_plural': 'Військовослужбовці',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('regular', 'звичайний рапорт'), ('custom', 'рапорт по специфічному шаблону')], default='regular', max_length=100, verbose_name='тип рапорту')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Назва рапорту')),
                ('body_sample', models.TextField(blank=True, null=True, verbose_name='зразок тексту рапорту')),
                ('body_template', models.TextField(blank=True, null=True, verbose_name='шаблон рапорту (змінюється адміністратором, див. у документації)')),
                ('default_footer_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_footer_position_set', to='reports.Position', verbose_name='посада від кого цей рапорт')),
                ('default_header_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_header_position_set', to='reports.Position', verbose_name='посада на кого цей рапорт')),
            ],
            options={
                'verbose_name': 'Рапорти__',
                'verbose_name_plural': 'Рапорти',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reports.Unit', verbose_name='підрозділ'),
        ),
    ]
