# Generated by Django 3.0.9 on 2020-08-03 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_tail',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='додаткова посада. Наприклад:(заступник начальника, перший заступник командира...)  !!! ___назву підрозділу НЕ ВКАЗУВАТИ___  !!!'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_title',
            field=models.CharField(max_length=255, verbose_name='посада (офіцер, старший офіцер, начальник)  ___назву підрозділу НЕ ВКАЗУВАТИ___  !!!'),
        ),
        migrations.AlterField(
            model_name='report',
            name='default_footer_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_footer_position_set', to='reports.Position', verbose_name="посада вiд кого цей рапорт. (ВКАЗУВАТИ ТIЛЬКИ ДЛЯ РАПОРТIВ типу: 'рапорт по специфічному шаблону')"),
        ),
        migrations.AlterField(
            model_name='report',
            name='default_header_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_header_position_set', to='reports.Position', verbose_name="посада на кого цей рапорт. (ВКАЗУВАТИ ТIЛЬКИ ДЛЯ РАПОРТIВ типу: 'рапорт по специфічному шаблону')"),
        ),
    ]
